# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    # ... autres configurations globales

    session:
        handler_id: session.handler.native_file
        cookie_secure: auto  # 'auto' s'adapte à HTTP/HTTPS
        cookie_samesite: 'lax'
        cookie_httponly: true
        cookie_path: '/'
        name: 'APP_SESSID'
        storage_factory_id: 'session.storage.factory.native'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        gc_maxlifetime: 14400
        gc_probability: 1
        gc_divisor: 100
        sid_length: 32
        sid_bits_per_character: 6